Adding comment parser to config parsing
APISquare/envone pull request #16
Opened 2020-10-08 16:42 UTC by mjnagel

Adding a parser to allow comments in the JSON and strip them out.

Provides an initial fix for issue #12 .

This could be improved with additional support for multiline comments and comments after a config value. Currently this just supports single inline comments where the entire line is commented out as in this case:

```
{
  "HOST": "https://abc.com",
  // "SERVER_URL": "{{BASE_URL}}/api/v1",
}
```

2020-10-10 02:10 UTC, suthagar23 requested changes

2020-10-10 02:10 UTC, suthagar23 commented on src/config.js
> +  return content.replace(/^\s*\/\/.*$\n/gm, '')
Missing semicolon as per the lint requirement.

2020-10-10 02:13 UTC, suthagar23 commented
Can you please write test cases for these examples, 

```
{
  "HOST": "https://abc.com",
  // "SERVER_URL": "{{BASE_URL}}/api/v1",
  "PORT": 8080
}

```

```
{
  "HOST": "https://abc.com",
  // "SERVER_URL": {
  //     "DEV": "{{BASE_URL}}/api/v1",
  //     "DEFAULT": "https://abc.com/api/v1",
  // },
  "PORT": 8080
}
```

2020-10-13 14:34 UTC, mjnagel commented
> Can you please write test cases for these examples,
> 
> ```
> {
>   "HOST": "https://abc.com",
>   // "SERVER_URL": "{{BASE_URL}}/api/v1",
>   "PORT": 8080
> }
> ```
> 
> ```
> {
>   "HOST": "https://abc.com",
>   // "SERVER_URL": {
>   //     "DEV": "{{BASE_URL}}/api/v1",
>   //     "DEFAULT": "https://abc.com/api/v1",
>   // },
>   "PORT": 8080
> }
> ```

Sorry I just saw this now @suthagar23 . Would you like me to add a new .env.config under the tests folder (something like .env-comments.config) or just add those commented lines to the current one? I want to make sure I'm following the best process for your current testing.

2020-10-15 03:26 UTC, suthagar23 commented
@mjnagel  I think, better to have everything in one `.env.config` file as the dependency searches for `.env.config` file.

2020-11-10 04:01 UTC, suthagar23 commented
@mjnagel Would you like to continue working on this?

2021-02-01 10:26 UTC, suthagar23 commented
Closing this pull request, Please re-open it when it's ready

2021-02-01 10:26 UTC, closed without merging